vcs:
  name: git
  main-branch: main

prerequisites:
  - working-copy-check:
        allow-ignore: true
  - display-last-changes
  - tests-check
  - composer-security-check
  - command:
        cmd: git remote -v


pre-release-actions:
    bin/UpdateApplicationVersionCurrentVersion.php: ~
    changelog-update:
        format: semantic
        dump-commits: true
        exclude-merge-commits: true
    vcs-commit: ~

version-generator: semantic
version-persister: vcs-tag

post-release-actions:
    vcs-publish:
        ask-remote-name: true
